tap homebrew/versions
update
tap phinze/cask
install ack
install autoconf
install automake
install brew-cask
install byobu
install cmake
install ctags
install coreutils
install cscope
install docbook
install docbook-xsl
install emacs
install fasd
install freetype
install git
install gdbm
install gettext
install gnu-getopt
install gnu-sed
install htop-osx
install hub
install icu4c
install imagemagick
install jpeg
install leiningen
install libxslt
install libyaml
install libevent
install libpng
install libtiff
install libtool
install libxml2
install lua
install macvim
install mercurial
install mongodb
install newt
install openssl
install ossp-uuid
install phantomjs
install postgresql
install protobuf
install python
install python3
install pcre
install pkg-config
install popt
install pstree
install rbenv-gem-rehash
install rbenv-gemset
install reattach-to-user-namespace
install redis
install ruby-build
install rbenv
install readline
install sdl_image
install ssh-copy-id
install s-lang
install scons
install sdl
install sqlite
install tmate
install tmux
install tor
install terminal-notifier
install the_silver_searcher
install tig
install tree
install v8
install vim
install watch
install wemux
install webp
install wget
install xmlto
install xz
install zsh
install zsh-completions
install zsh-history-substring-search
install zsh-lovers
install zsh-syntax-highlighting
install vim --override-system-vi
doctor
