install brew-cask
install byobu
install cmake
install ctags
install emacs
install fasd
install git
install htop-osx
install imagemagick
install leiningen
install libxslt
install libyaml
install macvim
install mercurial
install mongodb
install phantomjs
install postgresql
install protobuf
install pstree
install python
install python3
install rbenv-gem-rehash
install rbenv-gemset
install reattach-to-user-namespace
install redis
install ruby-build
install sdl_image
install ssh-copy-id
install terminal-notifier
install the_silver_searcher
install tig
install tree
install v8
install vim
install watch
install wemux
install wget
install xmlto
install zsh
install zsh-completions
install zsh-history-substring-search
install zsh-lovers
install zsh-syntax-highlighting
install ack
install vim --override-system-vi
tap homebrew/versions
update
doctor
